package com.thengoding.asistenhujan.models.current

import com.thengoding.asistenhujan.models.Weather

data class CurrentData(
    val app_temp: Double,
    val aqi: Int,
    val city_name: String,
    val clouds: Int,
    val country_code: String,
    val datetime: String,
    val dewpt: Int,
    val dhi: Double,
    val dni: Double,
    val elev_angle: Int,
    val ghi: Double,
    val hour_angle: Int,
    val lat: Int,
    val lon: Double,
    val ob_time: String,
    val pod: String,
    val precip: Int,
    val pres: Int,
    val rh: Int,
    val slp: Double,
    val snow: Int,
    val solar_rad: Double,
    val state_code: String,
    val station: String,
    val sunrise: String,
    val sunset: String,
    val temp: Double,
    val timezone: String,
    val ts: Int,
    val uv: Double,
    val vis: Int,
    val weather: Weather,
    val wind_cdir: String,
    val wind_cdir_full: String,
    val wind_dir: Int,
    val wind_speed: Double
)